
import { db } from '../firebaseConfig';
import { collection, writeBatch, doc } from 'firebase/firestore';
import { PEPProfile } from '../types';

const EALA_DATA = [
  { no: 1, name: "Hon. Andrew John Chenge", role: "Ex-Officio", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 2, name: "Hon. John Kibet Koech", role: "Ex-Officio", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 3, name: "Hon. Wilbert T Kaahwa", role: "Ex-Officio", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 4, name: "Hon. Juma Mwapachu", role: "Ex-Officio", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 5, name: "Hon. Jared Benson Kangwana", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 6, name: "Hon. Margaret J Kamar", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 7, name: "Hon. Adan Abdullahi", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 8, name: "Hon. Maxwell Shamala", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 9, name: "Hon. Abdirahim Haji. H. Abdi", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 10, name: "Hon. Mohamed Abdalla Zubedi", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 11, name: "Hon. Ochieng Gilbert Mbeo", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 12, name: "Hon. Calist A Mwatela", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 13, name: "Hon. Rose Wairimu Waruhiu", role: "Member", country: "Kenya", assembly: "1st Assembly 2001 - 2006" },
  { no: 14, name: "Hon. Ddudu Richard Baker", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 15, name: "Hon. Sheila K Mishambi", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 16, name: "Hon. Yonasani B Kanyomozi", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 17, name: "Hon. Daniel Wandera", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 18, name: "Hon. Sarah N Bagalaaliwo", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 19, name: "Hon. Mugisha Muntu Oyera", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 20, name: "Hon. Lydia Wanyoto Mutende", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 21, name: "Hon. Irene Odida Ovonji", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 22, name: "Hon. Med S. K Kaggwa", role: "Member", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 23, name: "Hon. Sheila Kate Kamba", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 24, name: "Hon. Hulda Kibacha", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 25, name: "Hon. Isaac A Sepetu", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 26, name: "Hon. Norman Sigalla", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 27, name: "Hon. Mabere Marando Nyaucho", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 28, name: "Hon. Said Bakari Jecha", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 29, name: "Hon. Mahfoudha Alley Hamid", role: "Member", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 30, name: "Hon. Abdulrahman O Kinana", role: "Speaker", country: "Tanzania", assembly: "1st Assembly 2001 - 2006" },
  { no: 31, name: "Hon. Eriya Kategeya", role: "Ex-Officio", country: "Uganda", assembly: "1st Assembly 2001 - 2006" },
  { no: 32, name: "Hon. Margaret Nantongo Zziwa", role: "Speaker", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 33, name: "Hon. Safina Kwekwe Tsungu", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 34, name: "Hon. Reuben Oyondi Oyondi", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 35, name: "Hon. Nusura Tiperu Omar", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 36, name: "Hon. Nzobonimpa Manasse", role: "Member", country: "Burundi", assembly: "2nd Assembly 2007 - 2012" },
  { no: 37, name: "Hon. Dan Wandera Ogalo", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 38, name: "Hon. Valerie Nyirahabineza", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 39, name: "Hon. Georgette Nibitanga", role: "Member", country: "Burundi", assembly: "2nd Assembly 2007 - 2012" },
  { no: 40, name: "Hon. Frederic Ngenzebuhoro", role: "Member", country: "Burundi", assembly: "2nd Assembly 2007 - 2012" },
  { no: 41, name: "Hon. Straton Ndikuryayo", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 42, name: "Hon. Janet Deo Mmari", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 43, name: "Hon. Leonce Ndarubagiye", role: "Member", country: "Burundi", assembly: "2nd Assembly 2007 - 2012" },
  { no: 44, name: "Hon. Sebtuu Mohamed Nassor", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 45, name: "Hon. Mugisha Oyera Muntu", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 46, name: "Hon. Bernard Mulengani", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 47, name: "Hon. Jacqueline Muhongayire", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 48, name: "Hon. Patricia Hajabakiga", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 49, name: "Hon. Augustine Loile Chemonges Lotodo", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 50, name: "Hon. Claire Kayirangwa", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 51, name: "Hon. Daniel Fred Kidega", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 52, name: "Hon. Regine Katabarumwe", role: "Member", country: "Burundi", assembly: "2nd Assembly 2007 - 2012" },
  { no: 53, name: "Hon. Said Gharib Bilal", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 54, name: "Hon. Pierre Damian Habumuremyi", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 55, name: "Hon. Odette Nyiramirimo", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 56, name: "Hon. James Ndahiro", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 57, name: "Hon. Didas John Massaburi", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 58, name: "Hon. Fortunatus Lwanyantika Masha", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 59, name: "Hon. Walid Aman Kabourou", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 60, name: "Hon. Dora Kanabahita Byamukama", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 61, name: "Hon. Abdul Karim Harerimana", role: "Member", country: "Rwanda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 62, name: "Hon. Sarah Talaso Bonaya", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 63, name: "Hon. Kate Sylivia, Magdalena Kamba", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 64, name: "Hon. Francois Bizimana", role: "Member", country: "Burundi", assembly: "2nd Assembly 2007 - 2012" },
  { no: 65, name: "Hon. Clarkson Otieno Karan", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 66, name: "Hon. Gervase Mathias Buluma Kafwa Akhaabi", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 67, name: "Hon. Abdullah Ali Hassan Mwinyi", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 68, name: "Hon. Lydia Wanyoto Wanyoto", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 69, name: "Hon. Mike Sebalu", role: "Member", country: "Uganda", assembly: "2nd Assembly 2007 - 2012" },
  { no: 70, name: "Hon. George Francis Nangale", role: "Member", country: "Tanzania", assembly: "2nd Assembly 2007 - 2012" },
  { no: 71, name: "Hon. Christopher Dove Nakuleu", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 72, name: "Hon. Catherine N Kimura", role: "Member", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 73, name: "Hon. Abdirahim Haithar Haji Abdi", role: "Speaker", country: "Kenya", assembly: "2nd Assembly 2007 - 2012" },
  { no: 74, name: "Hon. Kolimba Susan", role: "Ex-Officio", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 75, name: "Hon. Anthony Kafumbe", role: "Ex-Officio", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 76, name: "Hon. Liberat Mpfumukeko", role: "Ex-Officio", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 77, name: "Hon. Valentine Rugwabiza", role: "Ex-Officio", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 78, name: "Dr.. Augustine Philip Mahiga", role: "Ex-Officio", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 79, name: "Hon. Léontine Nzeyimana", role: "Ex-Officio", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 80, name: "Hon. Shem Bageine", role: "Ex-Officio", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 81, name: "Hon. Phyllis Kandie", role: "Ex-Officio", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 82, name: "Hon. Nusura O Tiperu", role: "Member", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 83, name: "Hon. Mike K Sebalu", role: "Member", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 84, name: "Hon. Chris Opoka Okumu", role: "Member", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 85, name: "Hon. Susan Nakawuki", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 86, name: "Hon. Margaret Nantongo Zziwa", role: "Member", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 87, name: "Hon. Bernard Kasangavu Mulengani", role: "Member", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 88, name: "Hon. Fred Mbidde Mukasa", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 89, name: "Hon. Daniel Fred Kidega", role: "Speaker", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 90, name: "Hon. Dora Kanabahita Byamukama", role: "Member", country: "Uganda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 91, name: "Hon. Maryam Ussi Yahya", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 92, name: "Hon. Issa Twaha Taslima", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 93, name: "Hon. Charles Makongoro Nyerere", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 94, name: "Hon. Perpetua Kessy Nderakindo", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 95, name: "Hon. Abdullah Ali Hassan Mwinyi", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 96, name: "Hon. Bernard Musomi Murunya", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 97, name: "Hon. Angela Charles Kizigha", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 98, name: "Hon. Adam Omar Kimbisa", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 99, name: "Hon. Shy-Rose Sadrudin Bhanji", role: "Member", country: "Tanzania", assembly: "3rd Assembly 2012 - 2017" },
  { no: 100, name: "Hon. Pierre-Celestin Rwigema", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 101, name: "Hon. Martin Ngoga", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 102, name: "Hon. Odette Nyiramilimo", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 103, name: "Hon. Valerie Nyirahabineza", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 104, name: "Hon. Straton Ndikuryayo", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 105, name: "Hon. James Ndahiro", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 106, name: "Hon. Francois Xavier Kalinda", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 107, name: "Hon. Patricia Mugorenejo Hajabakiga", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 108, name: "Hon. Gasinzigwa Oda", role: "Member", country: "Rwanda", assembly: "3rd Assembly 2012 - 2017" },
  { no: 109, name: "Hon. Judith Ramata Pareno", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 110, name: "Hon. Ombasa Joseph Kiangoi", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 111, name: "Hon. Abubakar D. Abdi Ogle", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 112, name: "Hon. Saoli Ole Nkanae", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 113, name: "Hon. Agnes Mumbi Ng'aru", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 114, name: "Hon. Peter Mutuku Mathuki", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 115, name: "Hon. Sarah T Bonaya", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 116, name: "Hon. Abubakar Zein Abubakar", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 117, name: "Hon. Nancy K. L Abisai", role: "Member", country: "Kenya", assembly: "3rd Assembly 2012 - 2017" },
  { no: 118, name: "Hon. Yves Nsabimana", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 119, name: "Hon. Frederic Ngenzebuhoro", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 120, name: "Hon. Jeremie Ngendakumana", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 121, name: "Hon. Emmanuel Nengo", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 122, name: "Hon. Martin Nduwimana", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 123, name: "Hon. Leonce Ndarubagiye", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 124, name: "Hon. Muhirwa Jean Marie", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 125, name: "Hon. Emerence Bucumi", role: "Member", country: "Burundi", assembly: "3rd Assembly 2012 - 2017" },
  { no: 126, name: "Hon. Isabelle Ndahayo", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 127, name: "Hon. Kadaga Rebecca", role: "Ex-Officio", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 128, name: "Hon. Mulamula Liberat", role: "Ex-Officio", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 129, name: "Hon. Nduwayo Christopher", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 130, name: "Hon. Burikukiye Victor", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 131, name: "Hon. Rurakamvye Pierre Claver", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 132, name: "Hon. Muhirwa Jean-Marie", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 133, name: "Hon. Karerwa Mo-Mamo", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 134, name: "Hon. Ahingejeje Alfred", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 135, name: "Hon. Nsavyimana Sophie", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 136, name: "Hon. Burikukiye Marie Claire", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 137, name: "Hon. Nzeyimana Léontine", role: "Member", country: "Burundi", assembly: "4th Assembly 2017- 2022" },
  { no: 138, name: "Hon. Gasinzigwa Oda", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 139, name: "Hon. Ndangiza Fatuma", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 140, name: "Hon. Rutazana Francine", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 141, name: "Hon. Uwumukiza Francoise", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 142, name: "Hon. Bahati Alex", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 143, name: "Hon. Barimuyabo Jean Claude", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 144, name: "Hon. Ngoga Martin", role: "Speaker", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 145, name: "Hon. Kalinda Francois Xavier", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 146, name: "Hon. Rwigema Pierre Celestin", role: "Member", country: "Rwanda", assembly: "4th Assembly 2017- 2022" },
  { no: 147, name: "Hon. Aburi Mpuru Lawrence", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 148, name: "Hon. Aden Omar Abdikadir", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 149, name: "Hon. Ali Ibrahim Fatuma", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 150, name: "Hon. Kalonzo Musyoka Kennedy", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 151, name: "Hon. Mbugua Nganga Simon", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 152, name: "Hon. Muhia Wanjiku", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 153, name: "Hon. Noor Mohamed Adan", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 154, name: "Hon. Oginga Oburu", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 155, name: "Hon. Sergon Jematiah Florence", role: "Member", country: "Kenya", assembly: "4th Assembly 2017- 2022" },
  { no: 156, name: "Hon. Mugyenyi Mary", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 157, name: "Hon. Akol Rose Okullu", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 158, name: "Hon. Kakooza James", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 159, name: "Hon. Musamali Paul Mwasa", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 160, name: "Hon. Namara Dennis", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 161, name: "Hon. Odongo George Stephen", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 162, name: "Hon. Mukasa Fred Mbidde", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 163, name: "Hon. Nakawuki Susan Nsambu", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 164, name: "Hon. Opoka Okumu Christopher", role: "Member", country: "Uganda", assembly: "4th Assembly 2017- 2022" },
  { no: 165, name: "Hon. Ayason Mukulia Kennedy", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 166, name: "Hon. Deng Nhial Gai", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 167, name: "Hon. DIING Alaak Garang Gabriel", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 168, name: "Hon. Deng Dut Gatkek Thomas", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 169, name: "Hon. Duop Gai Ruot Kim", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 170, name: "Hon. Gabriel Garang Aher Arol", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 171, name: "Hon. Leonardo Itti Ann", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 172, name: "Hon. Jago Odok Woda Jeremiah", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 173, name: "Hon. Thoar Gatpan Gideon", role: "Member", country: "South Sudan", assembly: "4th Assembly 2017- 2022" },
  { no: 174, name: "Hon. Lemoyan Josephine Sebastian", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 175, name: "Hon. Maasay Pamela Simon", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 176, name: "Hon. Ngwaru Maghembe", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 177, name: "Hon. Lugiko Happyness Elias", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 178, name: "Hon. Abdullah Hasnuu Makame", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 179, name: "Hon. Kimbisa Adam Omar", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 180, name: "Hon. Yahya Maryam Ussi", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 181, name: "Hon. Nkuhi Fancy Haji", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 182, name: "Hon. Mohamed Habib Mnyaa", role: "Member", country: "Tanzania", assembly: "4th Assembly 2017- 2022" },
  { no: 183, name: "Hon. Joseph Ntakirutimana", role: "Speaker", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 184, name: "Hon. Gabriel Ntisezerana", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 185, name: "Hon. Goreth BIGIRIMANA", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 186, name: "Hon. Victor Burikukiye", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 187, name: "Hon. Mo-Mamo Karerwa", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 188, name: "Hon. Cathy Kezimana", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 189, name: "Hon. Saidi Kibeya", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 190, name: "Hon. Anastase Manirambona", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 191, name: "Hon. Olivier Nkurunziza", role: "Member", country: "Burundi", assembly: "5th Assembly 2022 - 2027" },
  { no: 192, name: "Hon. Désiré Ipenda Boulu", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 193, name: "Hon. Jean Bertrand Is'ewanga Iwoka Ewanga", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 194, name: "Hon. Evariste Kwete Kalala", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 195, name: "Hon. Géraldine Kalwa Kaubo", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 196, name: "Hon. Jérémie Ilenda Maswama", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 197, name: "Hon. Joseph Mbombo Mundela", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 198, name: "Hon. Stella Nyota Mwetaminwa", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 199, name: "Hon. François Mangu Ngate", role: "Member", country: "Democratic Republic of Congo", assembly: "5th Assembly 2022 - 2027" },
  { no: 200, name: "Hon. Omar Hassan Hassan", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 201, name: "Hon. Deko Falhada Iman", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 202, name: "Hon. Kennedy Musyoka Kalonzo", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 203, name: "Hon. Kanini James Mathenge Kega", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 204, name: "Hon. Zipporah Kering Kurga", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 205, name: "Hon. Maina Godfrey Mwangi", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 206, name: "Hon. Winnie Irmgard Odinga", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 207, name: "Hon. David Ole Sankok", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 208, name: "Hon. Suleiman Said Shahbal", role: "Member", country: "Kenya", assembly: "5th Assembly 2022 - 2027" },
  { no: 210, name: "Hon. Caroline Rwivanga Kayonga", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 211, name: "Hon. Alodie Iradukunda", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 212, name: "Hon. Amb. Dr. Mathias Harebamungu", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 213, name: "Hon. Aisha Nyiramana", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 214, name: "Hon. Francine Rutazana", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 215, name: "Hon. Clément Musangabatware", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 216, name: "Hon. Françoise Uwumukiza", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 217, name: "Hon. Alex Bahati", role: "Member", country: "Rwanda", assembly: "5th Assembly 2022 - 2027" },
  { no: 218, name: "Hon. Gideon Gatpa Thoar", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 219, name: "Hon. Itto Anne Leonardo", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 220, name: "Hon. Odok Jeremiah Woda", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 221, name: "Hon. Kennedy Aysason Mukulia", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 222, name: "Hon. Gai Rut Kim", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 223, name: "Hon. Deng Gai", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 224, name: "Hon. Sebit James Sadia", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 225, name: "Hon. Thomson Luke Teny", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 226, name: "Hon. Aher Gabriel Garang Arol", role: "Member", country: "South Sudan", assembly: "5th Assembly 2022 - 2027" },
  { no: 227, name: "Hon. Ansar Kachwamba", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 228, name: "Hon. Angela Charles Kizigha", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 229, name: "Hon. Machano Ali Machano", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 230, name: "Hon. Abdulla Hasnuu Makame", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 231, name: "Hon. Ngole Khalfan Mashaka", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 232, name: "Hon. Salema Ladislaus Gladness", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 233, name: "Hon. Mohame Juma Nadra", role: "Member", country: "Tanzania", assembly: "5th Assembly 2022 - 2027" },
  { no: 234, name: "Hon. Rose Okullu Akol", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" },
  { no: 235, name: "Hon. Mary Rutamwebwa Mugyenyi", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" },
  { no: 236, name: "Hon. George Stephen Odongo", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" },
  { no: 237, name: "Hon. Paul Mwasa Musamali", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" },
  { no: 238, name: "Hon. Veronica Babirye Kadogo", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" },
  { no: 239, name: "Hon. Gerald Blacks Siranda", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" },
  { no: 240, name: "Hon. Jacquiline Amongin", role: "Member", country: "Uganda", assembly: "5th Assembly 2022 - 2027" }
];

export async function seedEALAHistoricalPEPs() {
  const batch = writeBatch(db);
  const pepsRef = collection(db, 'pep_profiles');

  EALA_DATA.forEach(p => {
    const docId = `eala-${p.no}`;
    const pep: PEPProfile = {
      id: docId,
      name: p.name,
      constituency: 'EALA / Regional Delegation',
      country: p.country,
      party: p.country === "Uganda" ? "NRM / EALA Delegation" : `${p.country} EALA`,
      category: 'Legislative Assembly',
      sentimentScore: 75,
      influenceIndex: 85,
      mentions: 450,
      confidence: '[TIER 5 — CONFIRMED]',
      intelligenceDossier: `EALA Historical Ledger Entry: Served in the ${p.assembly} as ${p.role}. Representing ${p.country}. This record is part of the sovereign intelligence node for regional political stability monitoring.`
    };
    
    const docRef = doc(pepsRef, docId);
    batch.set(docRef, pep);
  });

  await batch.commit();
  console.log('EALA Historical Ledger Synchronized.');
}
